### ISSUE TITLE
Test MonoDepth2

### ISSUE THREAD

**Issue by Kichkun** [MisterMap/undeepvo#38]
Запустить Monodepth2 и сравнить графики лосов

**Comment by Kichkun** [comment]
![image](https://user-images.githubusercontent.com/10221074/83676709-c933dd00-a5e3-11ea-9aec-cef00f4decdc.png)
![image](https://user-images.githubusercontent.com/10221074/83676839-fa141200-a5e3-11ea-9196-803c7c102fae.png)
![image](https://user-images.githubusercontent.com/10221074/83677033-41020780-a5e4-11ea-9113-2b2365c77ad5.png)

Тест на том же датасете и в тех же условиях, без масок

**Comment by kshpv** [comment]
Nice!! Good work, Nastya!
